/**
 * The full ISO 3166-1 country list: English name, the primary IANA zone, and
 * the Russian genitive form used by the "время <genitive>" label.
 *
 * Committed rather than derived from a package at runtime. The selector has to
 * resolve EVERY country offline and deterministically, and a country -> zone
 * default is a choice, not a computation: the raw CLDR/IANA territory lists
 * mark exclaves and link aliases as separate zones (Germany carries
 * Europe/Zurich, Vietnam carries Asia/Bangkok), so the primary zone for the
 * multi-zone countries below is picked by hand.
 *
 * Provenance: ISO codes, English names and zone membership from CLDR via
 * countries-and-timezones; zones verified to resolve against the moment-timezone
 * data used by tzdata.ts (see countries.test.ts). Bouvet Island (BV) is carried
 * by hand: the source package omits it, and it takes the zone of Norway, the
 * territory it belongs to.
 */

export interface IsoCountry {
  /** ISO 3166-1 alpha-2 code. */
  readonly code: string;
  readonly name: string;
  /** Primary IANA zone, the assumption made for this country. */
  readonly zone: string;
  /**
   * Russian genitive of the country name, for "время Германии". ICU can only
   * produce the nominative ("Германия"), and Russian needs the genitive here,
   * so the forms are written out rather than generated.
   */
  readonly ru: string;
}

export const ISO_COUNTRIES: readonly IsoCountry[] = [
  { code: 'AD', name: 'Andorra', zone: 'Europe/Andorra', ru: 'Андорры' },
  { code: 'AE', name: 'United Arab Emirates', zone: 'Asia/Dubai', ru: 'ОАЭ' },
  { code: 'AF', name: 'Afghanistan', zone: 'Asia/Kabul', ru: 'Афганистана' },
  { code: 'AG', name: 'Antigua & Barbuda', zone: 'America/Puerto_Rico', ru: 'Антигуа и Барбуды' },
  { code: 'AI', name: 'Anguilla', zone: 'America/Puerto_Rico', ru: 'Ангильи' },
  { code: 'AL', name: 'Albania', zone: 'Europe/Tirane', ru: 'Албании' },
  { code: 'AM', name: 'Armenia', zone: 'Asia/Yerevan', ru: 'Армении' },
  { code: 'AO', name: 'Angola', zone: 'Africa/Lagos', ru: 'Анголы' },
  { code: 'AQ', name: 'Antarctica', zone: 'Antarctica/McMurdo', ru: 'Антарктиды' },
  { code: 'AR', name: 'Argentina', zone: 'America/Argentina/Buenos_Aires', ru: 'Аргентины' },
  { code: 'AS', name: 'American Samoa', zone: 'Pacific/Pago_Pago', ru: 'Американского Самоа' },
  { code: 'AT', name: 'Austria', zone: 'Europe/Vienna', ru: 'Австрии' },
  { code: 'AU', name: 'Australia', zone: 'Australia/Sydney', ru: 'Австралии' },
  { code: 'AW', name: 'Aruba', zone: 'America/Puerto_Rico', ru: 'Арубы' },
  { code: 'AX', name: 'Åland Islands', zone: 'Europe/Helsinki', ru: 'Аландских островов' },
  { code: 'AZ', name: 'Azerbaijan', zone: 'Asia/Baku', ru: 'Азербайджана' },
  { code: 'BA', name: 'Bosnia & Herzegovina', zone: 'Europe/Belgrade', ru: 'Боснии и Герцеговины' },
  { code: 'BB', name: 'Barbados', zone: 'America/Barbados', ru: 'Барбадоса' },
  { code: 'BD', name: 'Bangladesh', zone: 'Asia/Dhaka', ru: 'Бангладеш' },
  { code: 'BE', name: 'Belgium', zone: 'Europe/Brussels', ru: 'Бельгии' },
  { code: 'BF', name: 'Burkina Faso', zone: 'Africa/Abidjan', ru: 'Буркина-Фасо' },
  { code: 'BG', name: 'Bulgaria', zone: 'Europe/Sofia', ru: 'Болгарии' },
  { code: 'BH', name: 'Bahrain', zone: 'Asia/Qatar', ru: 'Бахрейна' },
  { code: 'BI', name: 'Burundi', zone: 'Africa/Maputo', ru: 'Бурунди' },
  { code: 'BJ', name: 'Benin', zone: 'Africa/Lagos', ru: 'Бенина' },
  { code: 'BL', name: 'St. Barthélemy', zone: 'America/Puerto_Rico', ru: 'Сен-Бартелеми' },
  { code: 'BM', name: 'Bermuda', zone: 'Atlantic/Bermuda', ru: 'Бермудских островов' },
  { code: 'BN', name: 'Brunei', zone: 'Asia/Kuching', ru: 'Брунея' },
  { code: 'BO', name: 'Bolivia', zone: 'America/La_Paz', ru: 'Боливии' },
  { code: 'BQ', name: 'Caribbean Netherlands', zone: 'America/Puerto_Rico', ru: 'Бонэйра, Синт-Эстатиуса и Сабы' },
  { code: 'BR', name: 'Brazil', zone: 'America/Sao_Paulo', ru: 'Бразилии' },
  { code: 'BS', name: 'Bahamas', zone: 'America/Toronto', ru: 'Багам' },
  { code: 'BT', name: 'Bhutan', zone: 'Asia/Thimphu', ru: 'Бутана' },
  { code: 'BV', name: 'Bouvet Island', zone: 'Europe/Oslo', ru: 'острова Буве' },
  { code: 'BW', name: 'Botswana', zone: 'Africa/Maputo', ru: 'Ботсваны' },
  { code: 'BY', name: 'Belarus', zone: 'Europe/Minsk', ru: 'Беларуси' },
  { code: 'BZ', name: 'Belize', zone: 'America/Belize', ru: 'Белиза' },
  { code: 'CA', name: 'Canada', zone: 'America/Toronto', ru: 'Канады' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', zone: 'Asia/Yangon', ru: 'Кокосовых островов' },
  { code: 'CD', name: 'Congo - Kinshasa', zone: 'Africa/Kinshasa', ru: 'Демократической Республики Конго' },
  { code: 'CF', name: 'Central African Republic', zone: 'Africa/Lagos', ru: 'Центрально-Африканской Республики' },
  { code: 'CG', name: 'Congo - Brazzaville', zone: 'Africa/Lagos', ru: 'Республики Конго' },
  { code: 'CH', name: 'Switzerland', zone: 'Europe/Zurich', ru: 'Швейцарии' },
  { code: 'CI', name: 'Côte d’Ivoire', zone: 'Africa/Abidjan', ru: 'Кот-д’Ивуара' },
  { code: 'CK', name: 'Cook Islands', zone: 'Pacific/Rarotonga', ru: 'островов Кука' },
  { code: 'CL', name: 'Chile', zone: 'America/Santiago', ru: 'Чили' },
  { code: 'CM', name: 'Cameroon', zone: 'Africa/Lagos', ru: 'Камеруна' },
  { code: 'CN', name: 'China', zone: 'Asia/Shanghai', ru: 'Китая' },
  { code: 'CO', name: 'Colombia', zone: 'America/Bogota', ru: 'Колумбии' },
  { code: 'CR', name: 'Costa Rica', zone: 'America/Costa_Rica', ru: 'Коста-Рики' },
  { code: 'CU', name: 'Cuba', zone: 'America/Havana', ru: 'Кубы' },
  { code: 'CV', name: 'Cape Verde', zone: 'Atlantic/Cape_Verde', ru: 'Кабо-Верде' },
  { code: 'CW', name: 'Curaçao', zone: 'America/Puerto_Rico', ru: 'Кюрасао' },
  { code: 'CX', name: 'Christmas Island', zone: 'Asia/Bangkok', ru: 'острова Рождества' },
  { code: 'CY', name: 'Cyprus', zone: 'Asia/Nicosia', ru: 'Кипра' },
  { code: 'CZ', name: 'Czechia', zone: 'Europe/Prague', ru: 'Чехии' },
  { code: 'DE', name: 'Germany', zone: 'Europe/Berlin', ru: 'Германии' },
  { code: 'DJ', name: 'Djibouti', zone: 'Africa/Nairobi', ru: 'Джибути' },
  { code: 'DK', name: 'Denmark', zone: 'Europe/Berlin', ru: 'Дании' },
  { code: 'DM', name: 'Dominica', zone: 'America/Puerto_Rico', ru: 'Доминики' },
  { code: 'DO', name: 'Dominican Republic', zone: 'America/Santo_Domingo', ru: 'Доминиканской Республики' },
  { code: 'DZ', name: 'Algeria', zone: 'Africa/Algiers', ru: 'Алжира' },
  { code: 'EC', name: 'Ecuador', zone: 'America/Guayaquil', ru: 'Эквадора' },
  { code: 'EE', name: 'Estonia', zone: 'Europe/Tallinn', ru: 'Эстонии' },
  { code: 'EG', name: 'Egypt', zone: 'Africa/Cairo', ru: 'Египта' },
  { code: 'EH', name: 'Western Sahara', zone: 'Africa/El_Aaiun', ru: 'Западной Сахары' },
  { code: 'ER', name: 'Eritrea', zone: 'Africa/Nairobi', ru: 'Эритреи' },
  { code: 'ES', name: 'Spain', zone: 'Europe/Madrid', ru: 'Испании' },
  { code: 'ET', name: 'Ethiopia', zone: 'Africa/Nairobi', ru: 'Эфиопии' },
  { code: 'FI', name: 'Finland', zone: 'Europe/Helsinki', ru: 'Финляндии' },
  { code: 'FJ', name: 'Fiji', zone: 'Pacific/Fiji', ru: 'Фиджи' },
  { code: 'FK', name: 'Falkland Islands', zone: 'Atlantic/Stanley', ru: 'Фолклендских островов' },
  { code: 'FM', name: 'Micronesia', zone: 'Pacific/Pohnpei', ru: 'Федеративных Штатов Микронезии' },
  { code: 'FO', name: 'Faroe Islands', zone: 'Atlantic/Faroe', ru: 'Фарерских островов' },
  { code: 'FR', name: 'France', zone: 'Europe/Paris', ru: 'Франции' },
  { code: 'GA', name: 'Gabon', zone: 'Africa/Lagos', ru: 'Габона' },
  { code: 'GB', name: 'United Kingdom', zone: 'Europe/London', ru: 'Великобритании' },
  { code: 'GD', name: 'Grenada', zone: 'America/Puerto_Rico', ru: 'Гренады' },
  { code: 'GE', name: 'Georgia', zone: 'Asia/Tbilisi', ru: 'Грузии' },
  { code: 'GF', name: 'French Guiana', zone: 'America/Cayenne', ru: 'Французской Гвианы' },
  { code: 'GG', name: 'Guernsey', zone: 'Europe/London', ru: 'Гернси' },
  { code: 'GH', name: 'Ghana', zone: 'Africa/Abidjan', ru: 'Ганы' },
  { code: 'GI', name: 'Gibraltar', zone: 'Europe/Gibraltar', ru: 'Гибралтара' },
  { code: 'GL', name: 'Greenland', zone: 'America/Nuuk', ru: 'Гренландии' },
  { code: 'GM', name: 'Gambia', zone: 'Africa/Abidjan', ru: 'Гамбии' },
  { code: 'GN', name: 'Guinea', zone: 'Africa/Abidjan', ru: 'Гвинеи' },
  { code: 'GP', name: 'Guadeloupe', zone: 'America/Puerto_Rico', ru: 'Гваделупы' },
  { code: 'GQ', name: 'Equatorial Guinea', zone: 'Africa/Lagos', ru: 'Экваториальной Гвинеи' },
  { code: 'GR', name: 'Greece', zone: 'Europe/Athens', ru: 'Греции' },
  { code: 'GS', name: 'South Georgia & South Sandwich Islands', zone: 'Atlantic/South_Georgia', ru: 'Южной Георгии и Южных Сандвичевых островов' },
  { code: 'GT', name: 'Guatemala', zone: 'America/Guatemala', ru: 'Гватемалы' },
  { code: 'GU', name: 'Guam', zone: 'Pacific/Guam', ru: 'Гуама' },
  { code: 'GW', name: 'Guinea-Bissau', zone: 'Africa/Bissau', ru: 'Гвинеи-Бисау' },
  { code: 'GY', name: 'Guyana', zone: 'America/Guyana', ru: 'Гайаны' },
  { code: 'HK', name: 'Hong Kong SAR China', zone: 'Asia/Hong_Kong', ru: 'Гонконга' },
  { code: 'HM', name: 'Heard & McDonald Islands', zone: 'Indian/Kerguelen', ru: 'островов Херд и Макдональд' },
  { code: 'HN', name: 'Honduras', zone: 'America/Tegucigalpa', ru: 'Гондураса' },
  { code: 'HR', name: 'Croatia', zone: 'Europe/Belgrade', ru: 'Хорватии' },
  { code: 'HT', name: 'Haiti', zone: 'America/Port-au-Prince', ru: 'Гаити' },
  { code: 'HU', name: 'Hungary', zone: 'Europe/Budapest', ru: 'Венгрии' },
  { code: 'ID', name: 'Indonesia', zone: 'Asia/Jakarta', ru: 'Индонезии' },
  { code: 'IE', name: 'Ireland', zone: 'Europe/Dublin', ru: 'Ирландии' },
  { code: 'IL', name: 'Israel', zone: 'Asia/Jerusalem', ru: 'Израиля' },
  { code: 'IM', name: 'Isle of Man', zone: 'Europe/London', ru: 'острова Мэн' },
  { code: 'IN', name: 'India', zone: 'Asia/Kolkata', ru: 'Индии' },
  { code: 'IO', name: 'British Indian Ocean Territory', zone: 'Indian/Chagos', ru: 'Британской территории в Индийском океане' },
  { code: 'IQ', name: 'Iraq', zone: 'Asia/Baghdad', ru: 'Ирака' },
  { code: 'IR', name: 'Iran', zone: 'Asia/Tehran', ru: 'Ирана' },
  { code: 'IS', name: 'Iceland', zone: 'Africa/Abidjan', ru: 'Исландии' },
  { code: 'IT', name: 'Italy', zone: 'Europe/Rome', ru: 'Италии' },
  { code: 'JE', name: 'Jersey', zone: 'Europe/London', ru: 'Джерси' },
  { code: 'JM', name: 'Jamaica', zone: 'America/Jamaica', ru: 'Ямайки' },
  { code: 'JO', name: 'Jordan', zone: 'Asia/Amman', ru: 'Иордании' },
  { code: 'JP', name: 'Japan', zone: 'Asia/Tokyo', ru: 'Японии' },
  { code: 'KE', name: 'Kenya', zone: 'Africa/Nairobi', ru: 'Кении' },
  { code: 'KG', name: 'Kyrgyzstan', zone: 'Asia/Bishkek', ru: 'Киргизии' },
  { code: 'KH', name: 'Cambodia', zone: 'Asia/Bangkok', ru: 'Камбоджи' },
  { code: 'KI', name: 'Kiribati', zone: 'Pacific/Tarawa', ru: 'Кирибати' },
  { code: 'KM', name: 'Comoros', zone: 'Africa/Nairobi', ru: 'Комор' },
  { code: 'KN', name: 'St. Kitts & Nevis', zone: 'America/Puerto_Rico', ru: 'Сент-Китса и Невиса' },
  { code: 'KP', name: 'North Korea', zone: 'Asia/Pyongyang', ru: 'КНДР' },
  { code: 'KR', name: 'South Korea', zone: 'Asia/Seoul', ru: 'Республики Корея' },
  { code: 'KW', name: 'Kuwait', zone: 'Asia/Riyadh', ru: 'Кувейта' },
  { code: 'KY', name: 'Cayman Islands', zone: 'America/Panama', ru: 'Каймановых островов' },
  { code: 'KZ', name: 'Kazakhstan', zone: 'Asia/Almaty', ru: 'Казахстана' },
  { code: 'LA', name: 'Laos', zone: 'Asia/Bangkok', ru: 'Лаоса' },
  { code: 'LB', name: 'Lebanon', zone: 'Asia/Beirut', ru: 'Ливана' },
  { code: 'LC', name: 'St. Lucia', zone: 'America/Puerto_Rico', ru: 'Сент-Люсии' },
  { code: 'LI', name: 'Liechtenstein', zone: 'Europe/Zurich', ru: 'Лихтенштейна' },
  { code: 'LK', name: 'Sri Lanka', zone: 'Asia/Colombo', ru: 'Шри-Ланки' },
  { code: 'LR', name: 'Liberia', zone: 'Africa/Monrovia', ru: 'Либерии' },
  { code: 'LS', name: 'Lesotho', zone: 'Africa/Johannesburg', ru: 'Лесото' },
  { code: 'LT', name: 'Lithuania', zone: 'Europe/Vilnius', ru: 'Литвы' },
  { code: 'LU', name: 'Luxembourg', zone: 'Europe/Brussels', ru: 'Люксембурга' },
  { code: 'LV', name: 'Latvia', zone: 'Europe/Riga', ru: 'Латвии' },
  { code: 'LY', name: 'Libya', zone: 'Africa/Tripoli', ru: 'Ливии' },
  { code: 'MA', name: 'Morocco', zone: 'Africa/Casablanca', ru: 'Марокко' },
  { code: 'MC', name: 'Monaco', zone: 'Europe/Paris', ru: 'Монако' },
  { code: 'MD', name: 'Moldova', zone: 'Europe/Chisinau', ru: 'Молдовы' },
  { code: 'ME', name: 'Montenegro', zone: 'Europe/Belgrade', ru: 'Черногории' },
  { code: 'MF', name: 'St. Martin', zone: 'America/Puerto_Rico', ru: 'Сен-Мартена' },
  { code: 'MG', name: 'Madagascar', zone: 'Africa/Nairobi', ru: 'Мадагаскара' },
  { code: 'MH', name: 'Marshall Islands', zone: 'Pacific/Majuro', ru: 'Маршалловых Островов' },
  { code: 'MK', name: 'North Macedonia', zone: 'Europe/Belgrade', ru: 'Северной Македонии' },
  { code: 'ML', name: 'Mali', zone: 'Africa/Abidjan', ru: 'Мали' },
  { code: 'MM', name: 'Myanmar (Burma)', zone: 'Asia/Yangon', ru: 'Мьянмы' },
  { code: 'MN', name: 'Mongolia', zone: 'Asia/Ulaanbaatar', ru: 'Монголии' },
  { code: 'MO', name: 'Macao SAR China', zone: 'Asia/Macau', ru: 'Макао' },
  { code: 'MP', name: 'Northern Mariana Islands', zone: 'Pacific/Guam', ru: 'Северных Марианских островов' },
  { code: 'MQ', name: 'Martinique', zone: 'America/Martinique', ru: 'Мартиники' },
  { code: 'MR', name: 'Mauritania', zone: 'Africa/Abidjan', ru: 'Мавритании' },
  { code: 'MS', name: 'Montserrat', zone: 'America/Puerto_Rico', ru: 'Монтсеррата' },
  { code: 'MT', name: 'Malta', zone: 'Europe/Malta', ru: 'Мальты' },
  { code: 'MU', name: 'Mauritius', zone: 'Indian/Mauritius', ru: 'Маврикия' },
  { code: 'MV', name: 'Maldives', zone: 'Indian/Maldives', ru: 'Мальдив' },
  { code: 'MW', name: 'Malawi', zone: 'Africa/Maputo', ru: 'Малави' },
  { code: 'MX', name: 'Mexico', zone: 'America/Mexico_City', ru: 'Мексики' },
  { code: 'MY', name: 'Malaysia', zone: 'Asia/Kuala_Lumpur', ru: 'Малайзии' },
  { code: 'MZ', name: 'Mozambique', zone: 'Africa/Maputo', ru: 'Мозамбика' },
  { code: 'NA', name: 'Namibia', zone: 'Africa/Windhoek', ru: 'Намибии' },
  { code: 'NC', name: 'New Caledonia', zone: 'Pacific/Noumea', ru: 'Новой Каледонии' },
  { code: 'NE', name: 'Niger', zone: 'Africa/Lagos', ru: 'Нигера' },
  { code: 'NF', name: 'Norfolk Island', zone: 'Pacific/Norfolk', ru: 'острова Норфолк' },
  { code: 'NG', name: 'Nigeria', zone: 'Africa/Lagos', ru: 'Нигерии' },
  { code: 'NI', name: 'Nicaragua', zone: 'America/Managua', ru: 'Никарагуа' },
  { code: 'NL', name: 'Netherlands', zone: 'Europe/Brussels', ru: 'Нидерландов' },
  { code: 'NO', name: 'Norway', zone: 'Europe/Berlin', ru: 'Норвегии' },
  { code: 'NP', name: 'Nepal', zone: 'Asia/Kathmandu', ru: 'Непала' },
  { code: 'NR', name: 'Nauru', zone: 'Pacific/Nauru', ru: 'Науру' },
  { code: 'NU', name: 'Niue', zone: 'Pacific/Niue', ru: 'Ниуэ' },
  { code: 'NZ', name: 'New Zealand', zone: 'Pacific/Auckland', ru: 'Новой Зеландии' },
  { code: 'OM', name: 'Oman', zone: 'Asia/Dubai', ru: 'Омана' },
  { code: 'PA', name: 'Panama', zone: 'America/Panama', ru: 'Панамы' },
  { code: 'PE', name: 'Peru', zone: 'America/Lima', ru: 'Перу' },
  { code: 'PF', name: 'French Polynesia', zone: 'Pacific/Tahiti', ru: 'Французской Полинезии' },
  { code: 'PG', name: 'Papua New Guinea', zone: 'Pacific/Port_Moresby', ru: 'Папуа — Новой Гвинеи' },
  { code: 'PH', name: 'Philippines', zone: 'Asia/Manila', ru: 'Филиппин' },
  { code: 'PK', name: 'Pakistan', zone: 'Asia/Karachi', ru: 'Пакистана' },
  { code: 'PL', name: 'Poland', zone: 'Europe/Warsaw', ru: 'Польши' },
  { code: 'PM', name: 'St. Pierre & Miquelon', zone: 'America/Miquelon', ru: 'Сен-Пьера и Микелона' },
  { code: 'PN', name: 'Pitcairn Islands', zone: 'Pacific/Pitcairn', ru: 'островов Питкэрн' },
  { code: 'PR', name: 'Puerto Rico', zone: 'America/Puerto_Rico', ru: 'Пуэрто-Рико' },
  { code: 'PS', name: 'Palestinian Territories', zone: 'Asia/Hebron', ru: 'Палестинских территорий' },
  { code: 'PT', name: 'Portugal', zone: 'Europe/Lisbon', ru: 'Португалии' },
  { code: 'PW', name: 'Palau', zone: 'Pacific/Palau', ru: 'Палау' },
  { code: 'PY', name: 'Paraguay', zone: 'America/Asuncion', ru: 'Парагвая' },
  { code: 'QA', name: 'Qatar', zone: 'Asia/Qatar', ru: 'Катара' },
  { code: 'RE', name: 'Réunion', zone: 'Asia/Dubai', ru: 'Реюньона' },
  { code: 'RO', name: 'Romania', zone: 'Europe/Bucharest', ru: 'Румынии' },
  { code: 'RS', name: 'Serbia', zone: 'Europe/Belgrade', ru: 'Сербии' },
  { code: 'RU', name: 'Russia', zone: 'Europe/Moscow', ru: 'России' },
  { code: 'RW', name: 'Rwanda', zone: 'Africa/Maputo', ru: 'Руанды' },
  { code: 'SA', name: 'Saudi Arabia', zone: 'Asia/Riyadh', ru: 'Саудовской Аравии' },
  { code: 'SB', name: 'Solomon Islands', zone: 'Pacific/Guadalcanal', ru: 'Соломоновых Островов' },
  { code: 'SC', name: 'Seychelles', zone: 'Asia/Dubai', ru: 'Сейшельских Островов' },
  { code: 'SD', name: 'Sudan', zone: 'Africa/Khartoum', ru: 'Судана' },
  { code: 'SE', name: 'Sweden', zone: 'Europe/Berlin', ru: 'Швеции' },
  { code: 'SG', name: 'Singapore', zone: 'Asia/Singapore', ru: 'Сингапура' },
  { code: 'SH', name: 'St. Helena', zone: 'Africa/Abidjan', ru: 'острова Святой Елены' },
  { code: 'SI', name: 'Slovenia', zone: 'Europe/Belgrade', ru: 'Словении' },
  { code: 'SJ', name: 'Svalbard & Jan Mayen', zone: 'Europe/Berlin', ru: 'Шпицбергена и Ян-Майена' },
  { code: 'SK', name: 'Slovakia', zone: 'Europe/Prague', ru: 'Словакии' },
  { code: 'SL', name: 'Sierra Leone', zone: 'Africa/Abidjan', ru: 'Сьерра-Леоне' },
  { code: 'SM', name: 'San Marino', zone: 'Europe/Rome', ru: 'Сан-Марино' },
  { code: 'SN', name: 'Senegal', zone: 'Africa/Abidjan', ru: 'Сенегала' },
  { code: 'SO', name: 'Somalia', zone: 'Africa/Nairobi', ru: 'Сомали' },
  { code: 'SR', name: 'Suriname', zone: 'America/Paramaribo', ru: 'Суринама' },
  { code: 'SS', name: 'South Sudan', zone: 'Africa/Juba', ru: 'Южного Судана' },
  { code: 'ST', name: 'São Tomé & Príncipe', zone: 'Africa/Sao_Tome', ru: 'Сан-Томе и Принсипи' },
  { code: 'SV', name: 'El Salvador', zone: 'America/El_Salvador', ru: 'Сальвадора' },
  { code: 'SX', name: 'Sint Maarten', zone: 'America/Puerto_Rico', ru: 'Синт-Мартена' },
  { code: 'SY', name: 'Syria', zone: 'Asia/Damascus', ru: 'Сирии' },
  { code: 'SZ', name: 'Eswatini', zone: 'Africa/Johannesburg', ru: 'Эсватини' },
  { code: 'TC', name: 'Turks & Caicos Islands', zone: 'America/Grand_Turk', ru: 'Тёркс и Кайкос' },
  { code: 'TD', name: 'Chad', zone: 'Africa/Ndjamena', ru: 'Чада' },
  { code: 'TF', name: 'French Southern Territories', zone: 'Indian/Kerguelen', ru: 'Французских Южных территорий' },
  { code: 'TG', name: 'Togo', zone: 'Africa/Abidjan', ru: 'Того' },
  { code: 'TH', name: 'Thailand', zone: 'Asia/Bangkok', ru: 'Таиланда' },
  { code: 'TJ', name: 'Tajikistan', zone: 'Asia/Dushanbe', ru: 'Таджикистана' },
  { code: 'TK', name: 'Tokelau', zone: 'Pacific/Fakaofo', ru: 'Токелау' },
  { code: 'TL', name: 'Timor-Leste', zone: 'Asia/Dili', ru: 'Восточного Тимора' },
  { code: 'TM', name: 'Turkmenistan', zone: 'Asia/Ashgabat', ru: 'Туркменистана' },
  { code: 'TN', name: 'Tunisia', zone: 'Africa/Tunis', ru: 'Туниса' },
  { code: 'TO', name: 'Tonga', zone: 'Pacific/Tongatapu', ru: 'Тонги' },
  { code: 'TR', name: 'Türkiye', zone: 'Europe/Istanbul', ru: 'Турции' },
  { code: 'TT', name: 'Trinidad & Tobago', zone: 'America/Puerto_Rico', ru: 'Тринидада и Тобаго' },
  { code: 'TV', name: 'Tuvalu', zone: 'Pacific/Tarawa', ru: 'Тувалу' },
  { code: 'TW', name: 'Taiwan', zone: 'Asia/Taipei', ru: 'Тайваня' },
  { code: 'TZ', name: 'Tanzania', zone: 'Africa/Nairobi', ru: 'Танзании' },
  { code: 'UA', name: 'Ukraine', zone: 'Europe/Kyiv', ru: 'Украины' },
  { code: 'UG', name: 'Uganda', zone: 'Africa/Nairobi', ru: 'Уганды' },
  { code: 'UM', name: 'U.S. Outlying Islands', zone: 'Pacific/Pago_Pago', ru: 'Внешних малых островов (США)' },
  { code: 'US', name: 'United States', zone: 'America/New_York', ru: 'Соединённых Штатов' },
  { code: 'UY', name: 'Uruguay', zone: 'America/Montevideo', ru: 'Уругвая' },
  { code: 'UZ', name: 'Uzbekistan', zone: 'Asia/Tashkent', ru: 'Узбекистана' },
  { code: 'VA', name: 'Vatican City', zone: 'Europe/Rome', ru: 'Ватикана' },
  { code: 'VC', name: 'St. Vincent & Grenadines', zone: 'America/Puerto_Rico', ru: 'Сент-Винсента и Гренадин' },
  { code: 'VE', name: 'Venezuela', zone: 'America/Caracas', ru: 'Венесуэлы' },
  { code: 'VG', name: 'British Virgin Islands', zone: 'America/Puerto_Rico', ru: 'Виргинских островов (Великобритания)' },
  { code: 'VI', name: 'U.S. Virgin Islands', zone: 'America/Puerto_Rico', ru: 'Виргинских островов (США)' },
  { code: 'VN', name: 'Vietnam', zone: 'Asia/Ho_Chi_Minh', ru: 'Вьетнама' },
  { code: 'VU', name: 'Vanuatu', zone: 'Pacific/Efate', ru: 'Вануату' },
  { code: 'WF', name: 'Wallis & Futuna', zone: 'Pacific/Tarawa', ru: 'Уоллиса и Футуны' },
  { code: 'WS', name: 'Samoa', zone: 'Pacific/Apia', ru: 'Самоа' },
  { code: 'YE', name: 'Yemen', zone: 'Asia/Riyadh', ru: 'Йемена' },
  { code: 'YT', name: 'Mayotte', zone: 'Africa/Nairobi', ru: 'Майотты' },
  { code: 'ZA', name: 'South Africa', zone: 'Africa/Johannesburg', ru: 'Южно-Африканской Республики' },
  { code: 'ZM', name: 'Zambia', zone: 'Africa/Maputo', ru: 'Замбии' },
  { code: 'ZW', name: 'Zimbabwe', zone: 'Africa/Maputo', ru: 'Зимбабве' },
];
